=== tweej/GarageDoorOpener/config.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:element name="config">
        <xsd:complexType>
            <xsd:all>
                <xsd:element name="listen_port" type="Port" />
                <xsd:element name="listen_ip" type="IPv4Address" />
                <xsd:element name="keystore" type="xsd:string" minOccurs="1" />
                <xsd:element name="lockout" minOccurs="0">
                    <xsd:complexType>
                        <xsd:sequence minOccurs="1">
                            <xsd:element name="attempts" type="xsd:unsignedShort" maxOccurs="1" />
                            <xsd:element name="block_duration" type="xsd:unsignedInt" maxOccurs="1" />
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="email" minOccurs="0">
                    <xsd:complexType>
                        <xsd:sequence minOccurs="1">
                            <xsd:element name="sender" type="xsd:string" minOccurs="1" maxOccurs="1" />
                            <xsd:element name="recipients" type="EmailRecipients" />
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="keypassword" type="xsd:string" minOccurs="1" />
                <xsd:element name="codes" type="AccessCodeMap" maxOccurs="1" />
            </xsd:all>
        </xsd:complexType>
    </xsd:element>


    <xsd:complexType name="AccessCodeMap">
        <xsd:sequence>
            <xsd:element name="code" type="AccessCode" minOccurs="1" maxOccurs="unbounded" />
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="AccessCode">
        <xsd:all>
            <xsd:element name="enabled" type="xsd:boolean" />
            <xsd:element name="owner" type="xsd:string" minOccurs="1" />
            <xsd:element name="description" type="xsd:string" minOccurs="0" maxOccurs="1" />
            <xsd:element name="gpios" type="GPIOList" minOccurs="1" maxOccurs="1" />
            <xsd:element name="AccessConstraints" type="AccessConstraintsType" minOccurs="0" maxOccurs="1" />
        </xsd:all>

        <xsd:attribute name="value" type="xsd:string" use="required" />
    </xsd:complexType>


    <xsd:complexType name="AccessConstraintsType">
        <xsd:all>
            <xsd:element name="DayOfWeek" type="DayOfWeekConstraints" minOccurs="0" maxOccurs="1">
                <xsd:unique name="DOWUnique">
                    <xsd:selector xpath="Day" />
                    <xsd:field xpath="." />
                </xsd:unique>
            </xsd:element>
            <xsd:element name="TimeOfDay" type="TimeOfDayConstraints" minOccurs="0" maxOccurs="1" />
            <xsd:element name="DateTime" type="DateTimeConstraints" minOccurs="0" maxOccurs="1" />
        </xsd:all>
    </xsd:complexType>


    <xsd:complexType name="DayOfWeekConstraints">
        <xsd:sequence>
            <xsd:element name="Day" type="DayOfWeekEnum" minOccurs="1" maxOccurs="7" />
        </xsd:sequence>
    </xsd:complexType>


    <xsd:simpleType name="DayOfWeekEnum">
        <xsd:restriction base="xsd:normalizedString">
            <xsd:enumeration value="Sunday" />
            <xsd:enumeration value="Monday" />
            <xsd:enumeration value="Tuesday" />
            <xsd:enumeration value="Wednesday" />
            <xsd:enumeration value="Thursday" />
            <xsd:enumeration value="Friday" />
            <xsd:enumeration value="Saturday" />
        </xsd:restriction>
    </xsd:simpleType>
    
    <xsd:complexType name="TimeOfDayConstraints">
        <xsd:sequence>
            <xsd:element name="TimeRange" maxOccurs="unbounded">
                <xsd:complexType>
                    <xsd:attribute name="start" type="xsd:string" use="required" />
                    <xsd:attribute name="end"   type="xsd:string" use="required" />
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="DateTimeConstraints">
        <xsd:sequence>
            <xsd:element name="DateTimeRange" maxOccurs="unbounded">
                <xsd:complexType>
                    <xsd:attribute name="start" type="xsd:string" use="required" />
                    <xsd:attribute name="end"   type="xsd:string" use="required" />
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="EmailRecipients">
        <xsd:sequence>
            <xsd:element name="recipient" type="xsd:string" minOccurs="1" maxOccurs="unbounded" />
        </xsd:sequence>
    </xsd:complexType>

    <xsd:simpleType name="Port">
        <xsd:annotation>
            <xsd:documentation>
                Port number in the range [1, 65535].
            </xsd:documentation>
        </xsd:annotation>

        <xsd:restriction base="xsd:unsignedShort">
            <xsd:minInclusive value="1" />
        </xsd:restriction>
    </xsd:simpleType>


    <xsd:simpleType name="IPv4Address">
        <xsd:annotation>
            <xsd:documentation>
                IPv4 address in the dotted-decimal notation.
            </xsd:documentation>
        </xsd:annotation>

        <xsd:restriction base="xsd:string">
            <xsd:pattern value="((25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[0-9])\.){3}(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[0-9])"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="GPIOList">
        <xsd:restriction>
            <xsd:simpleType>
                <xsd:list itemType="xsd:unsignedShort" />
            </xsd:simpleType>
            <xsd:minLength value="1" />
        </xsd:restriction>
    </xsd:simpleType>

</xsd:schema>

=== tweej/GarageDoorOpener/config.xml
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="config.xsd">

    <!-- The IP address on which to listen for clients. This should normally be 0.0.0.0 -->
    <listen_ip>0.0.0.0</listen_ip>

    <!-- The TCP port on which to listen for clients. -->
    <listen_port>8888</listen_port>

    <!-- The path to the Java Keystore generated by generateKeystoreAndCertificate.sh -->
    <keystore>garage.jks</keystore>

    <!-- The password provided to generateKeystoreAndCertificate.sh. The fact that this is an element in the
    configuration file enables unattended startup. -->
    <keypassword>secretpassword</keypassword>

    <!-- This section contains variables to tune the server's ability to temporarily block clients which repeatedly
    submit incorrect codes. This section is optional. The feature can be disabled by removing this section from this
    file. -->
    <lockout>
        <!-- The number of incorrect code submissions an endpoint can attempt before being blocked for the duration
        specified by block_time -->
        <attempts>3</attempts>

        <!-- Seconds an endpoint will be prohibited from submitting codes after providing the number of incorrect codes
         specified by attempts -->
        <block_duration>180</block_duration>
    </lockout>

    <!-- This section defines all the valid codes, and a list of GPIOs that will pulse when the code is received. The
    AccessConstraints element is optional, as are each of its children, DayOfWeek, TimeOfDay, and DateTime. -->
    <codes>
        <code value="012345">
            <enabled>true</enabled>
            <owner>Me</owner>
            <description>Both sides</description>
            <gpios>2 16</gpios>
            <AccessConstraints>
                <DayOfWeek>
                    <Day>Saturday</Day>
                    <Day>Sunday</Day>
                    <Day>Monday</Day>
                </DayOfWeek>
                <TimeOfDay>
                    <TimeRange start="00:01:02" end="03:04:05" />
                    <TimeRange start="06:07:08" end="09:10:11" />
                    <TimeRange start="18:00:00" end="19:00:00" />
                </TimeOfDay>
                <DateTime>
                    <DateTimeRange start="2016-01-01T00:00:00" end="2017-01-01T00:00:00" />
                    <DateTimeRange start="2014-01-01T00:00:00" end="2015-01-01T00:00:00" />
                </DateTime>
            </AccessConstraints>
        </code>

        <code value="543210">
            <enabled>true</enabled>
            <owner>You</owner>
            <gpios>10</gpios>
        </code>
    </codes>

</config>
